import { db } from '../server/db';
import { events, venueComparisons, jobOpenings, jobPortals, tasks, hrEmployees } from '../shared/schema';

async function seedEvents() {
  console.log('Seeding events...');
  
  // Create events
  await db.insert(events).values([
    {
      id: '40342823-d377-4ba4-9715-587b4d903dea',
      name: 'Delhi IBS Day 1',
      description: 'International Business Seminar - Day 1: Introduction to China Sourcing & Import-Export Business',
      type: 'ibs',
      city: 'Delhi',
      venue: 'India Habitat Centre',
      venueAddress: 'Lodhi Road, New Delhi',
      date: new Date('2026-01-30'),
      endDate: new Date('2026-01-30'),
      capacity: 500,
      status: 'upcoming',
    },
    {
      id: '50342823-d377-4ba4-9715-587b4d903deb',
      name: 'Delhi IBS Day 2',
      description: 'International Business Seminar - Day 2: Advanced Strategies & Hands-on Workshop',
      type: 'ibs',
      city: 'Delhi',
      venue: 'India Habitat Centre',
      venueAddress: 'Lodhi Road, New Delhi',
      date: new Date('2026-01-31'),
      endDate: new Date('2026-01-31'),
      capacity: 500,
      status: 'upcoming',
    },
    {
      id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      name: 'Mumbai Canton Fair Preview',
      description: 'Pre-Canton Fair networking event',
      type: 'seminar',
      city: 'Mumbai',
      venue: 'Radisson Hotel Mumbai',
      venueAddress: 'Andheri East, Mumbai',
      date: new Date('2026-02-15'),
      endDate: new Date('2026-02-15'),
      capacity: 200,
      status: 'upcoming',
    },
    {
      id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
      name: 'Bangalore Sourcing Workshop',
      description: 'Hands-on workshop for China sourcing',
      type: 'ibs',
      city: 'Bangalore',
      venue: 'ITC Gardenia',
      venueAddress: 'Residency Road, Bangalore',
      date: new Date('2026-03-10'),
      endDate: new Date('2026-03-11'),
      capacity: 150,
      status: 'upcoming',
    },
    {
      id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
      name: 'Hyderabad Import Export Summit',
      description: 'Annual summit for import-export businesses',
      type: 'seminar',
      city: 'Hyderabad',
      venue: 'HICC',
      venueAddress: 'Madhapur, Hyderabad',
      date: new Date('2026-04-05'),
      endDate: new Date('2026-04-06'),
      capacity: 400,
      status: 'upcoming',
    },
    {
      id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
      name: 'Pune Entrepreneur Meetup',
      description: 'Networking event for Pune entrepreneurs',
      type: 'ibs',
      city: 'Pune',
      venue: 'JW Marriott Pune',
      venueAddress: 'Senapati Bapat Road, Pune',
      date: new Date('2026-05-20'),
      endDate: new Date('2026-05-20'),
      capacity: 100,
      status: 'upcoming',
    },
  ]).onConflictDoNothing();
  
  console.log('Created events');
  
  // Create venue comparisons
  await db.insert(venueComparisons).values([
    {
      city: 'Delhi',
      category: '5 Star',
      name: 'The Leela Palace',
      airportDistance: '15 km',
      location: 'Chanakyapuri, New Delhi',
      hallCapacity: 600,
      contactPhone: '+91 11 3933 1234',
      contactEmail: 'events.delhi@theleela.com',
      contactPerson: 'Mr. Sharma',
      status: 'available',
      pricePerDay: 800000,
    },
    {
      city: 'Delhi',
      category: '5 Star',
      name: 'India Habitat Centre',
      airportDistance: '18 km',
      location: 'Lodhi Road, New Delhi',
      hallCapacity: 500,
      contactPhone: '+91 11 2468 2222',
      contactEmail: 'events@indiahabitat.org',
      contactPerson: 'Ms. Gupta',
      status: 'available',
      pricePerDay: 400000,
    },
    {
      city: 'Mumbai',
      category: '5 Star',
      name: 'Radisson Hotel Mumbai',
      airportDistance: '6-8 km',
      location: 'Andheri East, Mumbai',
      hallCapacity: 400,
      contactPhone: '+91 9152035824',
      contactEmail: 'events.mumbai@radisson.com',
      contactPerson: 'Mr. Prem',
      status: 'available',
      pricePerDay: 350000,
    },
    {
      city: 'Mumbai',
      category: '5 Star',
      name: 'Taj Lands End',
      airportDistance: '12 km',
      location: 'Bandra West, Mumbai',
      hallCapacity: 500,
      contactPhone: '+91 22 6668 1234',
      contactEmail: 'events.landsend@tajhotels.com',
      contactPerson: 'Mr. Desai',
      status: 'available',
      pricePerDay: 700000,
    },
    {
      city: 'Bangalore',
      category: '5 Star',
      name: 'ITC Gardenia',
      airportDistance: '35 km',
      location: 'Residency Road, Bangalore',
      hallCapacity: 400,
      contactPhone: '+91 80 2211 9898',
      contactEmail: 'events.gardenia@itchotels.in',
      contactPerson: 'Ms. Rao',
      status: 'available',
      pricePerDay: 500000,
    },
    {
      city: 'Hyderabad',
      category: '5 Star',
      name: 'HICC',
      airportDistance: '30 km',
      location: 'Madhapur, Hyderabad',
      hallCapacity: 1000,
      contactPhone: '+91 40 6682 3456',
      contactEmail: 'events@hicc.com',
      contactPerson: 'Mr. Reddy',
      status: 'available',
      pricePerDay: 600000,
    },
    {
      city: 'Chennai',
      category: '5 Star',
      name: 'ITC Grand Chola',
      airportDistance: '10 km',
      location: 'Guindy, Chennai',
      hallCapacity: 700,
      contactPhone: '+91 44 2220 0000',
      contactEmail: 'events.grandchola@itchotels.in',
      contactPerson: 'Mr. Krishnan',
      status: 'available',
      pricePerDay: 550000,
    },
    {
      city: 'Kolkata',
      category: '5 Star',
      name: 'JW Marriott Kolkata',
      airportDistance: '8 km',
      location: 'EM Bypass, Kolkata',
      hallCapacity: 350,
      contactPhone: '+91 33 6633 0000',
      contactEmail: 'events.kolkata@marriott.com',
      contactPerson: 'Ms. Banerjee',
      status: 'available',
      pricePerDay: 400000,
    },
    {
      city: 'Pune',
      category: '5 Star',
      name: 'JW Marriott Hotel Pune',
      airportDistance: '12 km',
      location: 'Senapati Bapat Road, Pune',
      hallCapacity: 300,
      contactPhone: '+91 20 6683 3333',
      contactEmail: 'events.pune@marriott.com',
      contactPerson: 'Mr. Kulkarni',
      status: 'available',
      pricePerDay: 380000,
    },
    {
      city: 'Ahmedabad',
      category: '5 Star',
      name: 'Hyatt Regency Ahmedabad',
      airportDistance: '8 km',
      location: 'Ashram Road, Ahmedabad',
      hallCapacity: 250,
      contactPhone: '+91 79 6619 1234',
      contactEmail: 'events.ahmedabad@hyatt.com',
      contactPerson: 'Mr. Patel',
      status: 'available',
      pricePerDay: 320000,
    },
  ]).onConflictDoNothing();
  
  console.log('Created venue comparisons');
  
  // Create job openings
  await db.insert(jobOpenings).values([
    {
      title: 'Sales Executive',
      department: 'Sales',
      location: 'Delhi',
      type: 'full-time',
      experience: '1-3 years',
      salary: '25000-35000',
      description: 'Looking for enthusiastic sales executives to join our team',
      requirements: ['Excellent communication skills', 'Sales experience preferred', 'Fluent in English and Hindi'],
      status: 'active',
      openings: 5,
    },
    {
      title: 'Business Development Manager',
      department: 'Sales',
      location: 'Mumbai',
      type: 'full-time',
      experience: '5-8 years',
      salary: '60000-80000',
      description: 'Senior role for driving business growth',
      requirements: ['MBA preferred', 'B2B sales experience', 'Team management'],
      status: 'active',
      openings: 2,
    },
    {
      title: 'HR Executive',
      department: 'HR',
      location: 'Delhi',
      type: 'full-time',
      experience: '2-4 years',
      salary: '30000-40000',
      description: 'HR professional for recruitment',
      requirements: ['HR certification', 'Recruitment experience'],
      status: 'active',
      openings: 1,
    },
    {
      title: 'Digital Marketing Specialist',
      department: 'Marketing',
      location: 'Remote',
      type: 'full-time',
      experience: '2-5 years',
      salary: '35000-50000',
      description: 'Digital marketing expert',
      requirements: ['Google Ads certified', 'Social media expertise'],
      status: 'active',
      openings: 1,
    },
    {
      title: 'Customer Support Executive',
      department: 'Operations',
      location: 'Delhi',
      type: 'full-time',
      experience: '0-2 years',
      salary: '18000-25000',
      description: 'Customer support',
      requirements: ['Good communication', 'Problem-solving'],
      status: 'active',
      openings: 3,
    },
    {
      title: 'Accounts Executive',
      department: 'Finance',
      location: 'Delhi',
      type: 'full-time',
      experience: '2-4 years',
      salary: '28000-38000',
      description: 'Accounting professional',
      requirements: ['B.Com/M.Com', 'Tally proficiency'],
      status: 'active',
      openings: 1,
    },
    {
      title: 'Content Writer',
      department: 'Marketing',
      location: 'Remote',
      type: 'contract',
      experience: '1-3 years',
      salary: '20000-30000',
      description: 'Content writer',
      requirements: ['Excellent writing', 'SEO knowledge'],
      status: 'active',
      openings: 2,
    },
    {
      title: 'China Sourcing Specialist',
      department: 'Operations',
      location: 'Delhi',
      type: 'full-time',
      experience: '3-5 years',
      salary: '45000-60000',
      description: 'China sourcing specialist',
      requirements: ['Mandarin proficiency', 'China experience'],
      status: 'active',
      openings: 1,
    },
    {
      title: 'Event Coordinator',
      department: 'Events',
      location: 'Delhi',
      type: 'full-time',
      experience: '2-4 years',
      salary: '30000-40000',
      description: 'Event coordinator',
      requirements: ['Event management', 'Vendor coordination'],
      status: 'active',
      openings: 2,
    },
    {
      title: 'Graphic Designer',
      department: 'Marketing',
      location: 'Remote',
      type: 'contract',
      experience: '2-4 years',
      salary: '25000-35000',
      description: 'Graphic designer',
      requirements: ['Adobe Creative Suite', 'Portfolio required'],
      status: 'active',
      openings: 1,
    },
  ]).onConflictDoNothing();
  
  console.log('Created job openings');
  
  // Create job portals
  await db.insert(jobPortals).values([
    {
      name: 'Naukri.com',
      url: 'https://www.naukri.com',
      isActive: true,
      credentials: { username: 'suprans_hr', lastLogin: '2026-01-20' },
    },
    {
      name: 'LinkedIn',
      url: 'https://www.linkedin.com',
      isActive: true,
      credentials: { username: 'suprans_careers', lastLogin: '2026-01-22' },
    },
    {
      name: 'WorkIndia',
      url: 'https://www.workindia.in',
      isActive: true,
      credentials: { username: 'suprans', lastLogin: '2026-01-21' },
    },
    {
      name: 'Indeed',
      url: 'https://www.indeed.co.in',
      isActive: true,
      credentials: { username: 'suprans_jobs', lastLogin: '2026-01-19' },
    },
    {
      name: 'Shine',
      url: 'https://www.shine.com',
      isActive: false,
      credentials: { username: 'suprans_hr', lastLogin: '2026-01-10' },
    },
  ]).onConflictDoNothing();
  
  console.log('Created job portals');

  console.log('Events and related data seeded successfully!');
}

seedEvents()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
