import { db } from '../server/db';
import { hrEmployees, tasks, assets } from '../shared/schema';

async function seedHrData() {
  console.log('Seeding HR employees...');
  
  // First get the users
  const usersResult = await db.query.users.findMany();
  const adminUser = usersResult.find(u => u.role === 'superadmin');
  const salesUser = usersResult.find(u => u.role === 'sales_executive');
  
  // Create HR employees
  await db.insert(hrEmployees).values([
    {
      employeeId: 'EMP001',
      name: 'Rahul Sharma',
      email: 'rahul.sharma@suprans.com',
      phone: '+91 9876543210',
      department: 'Sales',
      designation: 'Senior Sales Executive',
      officeUnit: 'Delhi HQ',
      joiningDate: new Date('2020-03-15'),
      status: 'active',
      isSalesTeam: true,
      reportingTo: adminUser?.id,
      salary: 45000,
      bankDetails: { bank: 'HDFC Bank', account: '1234567890', ifsc: 'HDFC0001234' },
    },
    {
      employeeId: 'EMP002',
      name: 'Priya Patel',
      email: 'priya.patel@suprans.com',
      phone: '+91 9876543211',
      department: 'Sales',
      designation: 'Sales Executive',
      officeUnit: 'Mumbai',
      joiningDate: new Date('2021-06-01'),
      status: 'active',
      isSalesTeam: true,
      reportingTo: adminUser?.id,
      salary: 35000,
    },
    {
      employeeId: 'EMP003',
      name: 'Amit Kumar',
      email: 'amit.kumar@suprans.com',
      phone: '+91 9876543212',
      department: 'Operations',
      designation: 'Operations Manager',
      officeUnit: 'Delhi HQ',
      joiningDate: new Date('2019-01-10'),
      status: 'active',
      isSalesTeam: false,
      salary: 55000,
    },
    {
      employeeId: 'EMP004',
      name: 'Neha Singh',
      email: 'neha.singh@suprans.com',
      phone: '+91 9876543213',
      department: 'HR',
      designation: 'HR Manager',
      officeUnit: 'Delhi HQ',
      joiningDate: new Date('2018-08-20'),
      status: 'active',
      isSalesTeam: false,
      salary: 50000,
    },
    {
      employeeId: 'EMP005',
      name: 'Vikram Reddy',
      email: 'vikram.reddy@suprans.com',
      phone: '+91 9876543214',
      department: 'Sales',
      designation: 'Business Development Manager',
      officeUnit: 'Hyderabad',
      joiningDate: new Date('2020-11-05'),
      status: 'active',
      isSalesTeam: true,
      salary: 60000,
    },
    {
      employeeId: 'EMP006',
      name: 'Anjali Gupta',
      email: 'anjali.gupta@suprans.com',
      phone: '+91 9876543215',
      department: 'Marketing',
      designation: 'Digital Marketing Specialist',
      officeUnit: 'Delhi HQ',
      joiningDate: new Date('2022-02-14'),
      status: 'active',
      isSalesTeam: false,
      salary: 40000,
    },
    {
      employeeId: 'EMP007',
      name: 'Rajesh Menon',
      email: 'rajesh.menon@suprans.com',
      phone: '+91 9876543216',
      department: 'Finance',
      designation: 'Accounts Manager',
      officeUnit: 'Delhi HQ',
      joiningDate: new Date('2017-04-12'),
      status: 'active',
      isSalesTeam: false,
      salary: 48000,
    },
    {
      employeeId: 'EMP008',
      name: 'Kavita Joshi',
      email: 'kavita.joshi@suprans.com',
      phone: '+91 9876543217',
      department: 'Sales',
      designation: 'Sales Executive',
      officeUnit: 'Pune',
      joiningDate: new Date('2023-01-09'),
      status: 'active',
      isSalesTeam: true,
      salary: 32000,
    },
    {
      employeeId: 'EMP009',
      name: 'Suresh Nair',
      email: 'suresh.nair@suprans.com',
      phone: '+91 9876543218',
      department: 'Events',
      designation: 'Event Coordinator',
      officeUnit: 'Delhi HQ',
      joiningDate: new Date('2021-09-20'),
      status: 'active',
      isSalesTeam: false,
      salary: 35000,
    },
    {
      employeeId: 'EMP010',
      name: 'Deepa Krishnan',
      email: 'deepa.krishnan@suprans.com',
      phone: '+91 9876543219',
      department: 'Operations',
      designation: 'China Sourcing Specialist',
      officeUnit: 'Delhi HQ',
      joiningDate: new Date('2019-07-15'),
      status: 'active',
      isSalesTeam: false,
      salary: 55000,
    },
    {
      employeeId: 'EMP011',
      name: 'Mohammed Farhan',
      email: 'farhan@suprans.com',
      phone: '+91 9876543220',
      department: 'Sales',
      designation: 'Sales Executive',
      officeUnit: 'Bangalore',
      joiningDate: new Date('2022-05-10'),
      status: 'active',
      isSalesTeam: true,
      salary: 33000,
    },
    {
      employeeId: 'EMP012',
      name: 'Lakshmi Iyer',
      email: 'lakshmi.iyer@suprans.com',
      phone: '+91 9876543221',
      department: 'Customer Support',
      designation: 'Customer Support Lead',
      officeUnit: 'Chennai',
      joiningDate: new Date('2020-02-28'),
      status: 'active',
      isSalesTeam: false,
      salary: 38000,
    },
  ]).onConflictDoNothing();
  
  console.log('Created HR employees');
  
  // Create tasks
  if (salesUser) {
    await db.insert(tasks).values([
      {
        title: 'Follow up with TechCorp lead',
        description: 'Call Alice Johnson regarding web development proposal',
        status: 'todo',
        priority: 'high',
        dueDate: new Date('2026-01-25'),
        assignedTo: salesUser.id,
        tags: ['sales', 'follow-up'],
      },
      {
        title: 'Prepare Canton Fair presentation',
        description: 'Create slides for upcoming client presentation',
        status: 'in_progress',
        priority: 'high',
        dueDate: new Date('2026-01-28'),
        assignedTo: salesUser.id,
        tags: ['presentation', 'canton-fair'],
      },
      {
        title: 'Update CRM with new leads',
        description: 'Add leads from last week networking event',
        status: 'todo',
        priority: 'medium',
        dueDate: new Date('2026-01-24'),
        assignedTo: salesUser.id,
        tags: ['crm', 'data-entry'],
      },
      {
        title: 'Send proposal to StartupXYZ',
        description: 'Complete and send mobile app development proposal',
        status: 'review',
        priority: 'high',
        dueDate: new Date('2026-01-23'),
        assignedTo: salesUser.id,
        tags: ['proposal', 'mobile-app'],
      },
    ]).onConflictDoNothing();
    
    console.log('Created tasks');
  }
  
  // Create assets
  await db.insert(assets).values([
    {
      assetId: 'AST001',
      name: 'Dell Latitude 5520 Laptop',
      category: 'Laptop',
      brand: 'Dell',
      model: 'Latitude 5520',
      serialNumber: 'DL5520-2024-001',
      purchaseDate: new Date('2024-03-15'),
      purchasePrice: 75000,
      status: 'assigned',
      condition: 'good',
      location: 'Delhi HQ',
    },
    {
      assetId: 'AST002',
      name: 'iPhone 14 Pro',
      category: 'Mobile',
      brand: 'Apple',
      model: 'iPhone 14 Pro',
      serialNumber: 'IP14PRO-2024-001',
      purchaseDate: new Date('2024-01-10'),
      purchasePrice: 129900,
      status: 'assigned',
      condition: 'excellent',
      location: 'Delhi HQ',
    },
    {
      assetId: 'AST003',
      name: 'HP LaserJet Pro Printer',
      category: 'Printer',
      brand: 'HP',
      model: 'LaserJet Pro M404dn',
      serialNumber: 'HPLJ-2023-001',
      purchaseDate: new Date('2023-06-20'),
      purchasePrice: 32000,
      status: 'available',
      condition: 'good',
      location: 'Delhi HQ',
    },
    {
      assetId: 'AST004',
      name: 'Lenovo ThinkPad X1 Carbon',
      category: 'Laptop',
      brand: 'Lenovo',
      model: 'ThinkPad X1 Carbon Gen 11',
      serialNumber: 'LNX1C-2024-001',
      purchaseDate: new Date('2024-05-08'),
      purchasePrice: 145000,
      status: 'assigned',
      condition: 'excellent',
      location: 'Mumbai',
    },
    {
      assetId: 'AST005',
      name: 'Samsung Galaxy S24 Ultra',
      category: 'Mobile',
      brand: 'Samsung',
      model: 'Galaxy S24 Ultra',
      serialNumber: 'SGS24U-2024-001',
      purchaseDate: new Date('2024-02-25'),
      purchasePrice: 134999,
      status: 'available',
      condition: 'excellent',
      location: 'Delhi HQ',
    },
    {
      assetId: 'AST006',
      name: 'Canon EOS R6 Camera',
      category: 'Camera',
      brand: 'Canon',
      model: 'EOS R6 Mark II',
      serialNumber: 'CANR6-2023-001',
      purchaseDate: new Date('2023-11-15'),
      purchasePrice: 215000,
      status: 'available',
      condition: 'excellent',
      location: 'Delhi HQ',
    },
    {
      assetId: 'AST007',
      name: 'Dell UltraSharp Monitor',
      category: 'Monitor',
      brand: 'Dell',
      model: 'U2722D',
      serialNumber: 'DLMON-2024-001',
      purchaseDate: new Date('2024-04-10'),
      purchasePrice: 38000,
      status: 'assigned',
      condition: 'good',
      location: 'Delhi HQ',
    },
    {
      assetId: 'AST008',
      name: 'MacBook Pro 14"',
      category: 'Laptop',
      brand: 'Apple',
      model: 'MacBook Pro 14" M3 Pro',
      serialNumber: 'MBP14-2024-001',
      purchaseDate: new Date('2024-06-01'),
      purchasePrice: 199900,
      status: 'assigned',
      condition: 'excellent',
      location: 'Bangalore',
    },
  ]).onConflictDoNothing();
  
  console.log('Created assets');
  
  console.log('HR data seeded successfully!');
}

seedHrData()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
